### ISSUE TITLE
Data type mismatched for domiciliation field

### ISSUE THREAD

**Issue by cuongnguyentan** [webeweb/pappers-library#1]
https://github.com/webeweb/pappers-library/blob/ca1b19bef8fd5f654be0d32da2c3f4d7dba94a93/src/Model/Etablissement.php#L297

Firstly, thank you for the open source.

I'm having the issue where the field domiciliation in Etablissement is of type object array, not of type string, as indicated in the api documentation:

![image](https://github.com/webeweb/pappers-library/assets/16044444/1b2a9991-43aa-4c7d-80a8-f73508eb9bad)

This results in the error
`Argument 1 passed to WBW\Library\Pappers\Model\Etablissement::setDomiciliation() must be of the type string or null, array given`

Would be great if you can update the model or give instruction on how I can contribute.

Thank you.

**Comment by webeweb** [comment]
Hi,

I have introduce a new model "Domiciliation" in the response parsing.

Can you update your project and test again to check this improvements ?

Best regards

**Comment by cuongnguyentan** [comment]
Thank you, it works for the domiciliation field now

But now I've got another error for the field rnm
`Argument 1 passed to WBW\Library\Pappers\Model\Entreprise::setRnm() must be of the type string or null, array given`

![image](https://github.com/webeweb/pappers-library/assets/16044444/03db5e89-c2b3-4bba-b96e-b053a01f3bf9)

**Comment by webeweb** [comment]
Please, update with the last changes and test again.

Thanks you for your feedback

**Comment by cuongnguyentan** [comment]
I've tried again with the latest code and it works fine for our project now.
Thank you for your support

**Comment by webeweb** [comment]
You're welcome.

Best regards
